"use client";

import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Bot, ChartNoAxesCombined, Check, ChevronDown, Layers3, MessageSquareText, Sparkles, Workflow } from "lucide-react";
import Link from "next/link";

const capabilities = [
  { number: "01", title: "Revenue growth", icon: ChartNoAxesCombined, items: ["Business growth strategy", "Revenue optimization", "Sales process improvement", "Customer acquisition systems"] },
  { number: "02", title: "Pipeline creation", icon: MessageSquareText, items: ["B2B lead generation", "Appointment setting", "Cold email & LinkedIn outreach", "Sales development & prospect research"] },
  { number: "03", title: "Retention & recovery", icon: Workflow, items: ["Customer reactivation", "Booking recovery", "Dormant lead reactivation", "Follow-up systems"] },
  { number: "04", title: "AI & automation", icon: Bot, items: ["AI chatbots & voice agents", "CRM and workflow automation", "Email & WhatsApp automation", "Internal business automation"] },
  { number: "05", title: "Digital systems", icon: Layers3, items: ["Websites & landing pages", "Client portals & dashboards", "Custom business tools", "AI strategy & digital transformation"] },
];

const industries = ["Marketing agencies", "Software companies", "Law & accounting firms", "Medical & dental clinics", "Real estate companies", "Home service businesses", "Consulting firms", "Financial services", "Educational organizations", "Recruitment agencies", "Hospitality businesses", "AI & web agencies"];

const process = [
  ["01", "Understand", "We map your revenue goal, bottlenecks, team, tools, and the cost of staying where you are."],
  ["02", "Prioritise", "We identify the most valuable next move—not the loudest or most fashionable one."],
  ["03", "Build", "Our team, specialist partners, or proprietary systems execute with one accountable owner: CannumX."],
  ["04", "Compound", "We measure the result, refine the system, and turn what works into the next layer of growth."],
];

function Reveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  return <motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: .55, delay }}>{children}</motion.div>;
}

export default function Home() {
  return <main className="overflow-hidden bg-[#102019] text-[#f3f2ec]">
    <section id="home" className="hero-grid relative min-h-[calc(100vh-5rem)] overflow-hidden px-5 pb-16 pt-24 sm:px-8 lg:px-12">
      <div className="pointer-events-none absolute inset-0 paper-noise opacity-30" />
      <div className="relative mx-auto flex min-h-[calc(100vh-11rem)] max-w-7xl flex-col justify-between">
        <Reveal><div className="eyebrow flex items-center gap-2 text-[10px] text-[#caff5a]"><Sparkles size={13} /> Revenue growth · AI systems · automation</div></Reveal>
        <div className="grid gap-10 py-16 lg:grid-cols-[1.35fr_.65fr] lg:items-end">
          <Reveal delay={.08}><h1 className="editorial-title max-w-4xl text-[clamp(4rem,10vw,9rem)] font-medium leading-[.82] tracking-[-.09em]">Growth, <em className="font-serif font-normal text-[#caff5a]">engineered</em><br />for momentum.</h1></Reveal>
          <Reveal delay={.16}><div className="max-w-md lg:pb-3"><p className="text-lg leading-8 text-[#f3f2ec]/70">CannumX helps businesses acquire customers, grow revenue, and operate with more leverage—through strategy, systems, and AI.</p><Link href="/contact" className="button-lime mt-8 inline-flex items-center gap-3 rounded-full px-6 py-3.5 font-semibold transition">Start a growth conversation <ArrowDownRight size={18} /></Link></div></Reveal>
        </div>
        <div className="flex items-center justify-between border-t border-white/15 pt-5 text-[10px] uppercase tracking-[.16em] text-white/45"><span>Built for businesses ready to move</span><span>Scroll to explore ↓</span></div>
      </div>
    </section>

    <section className="bg-[#f3f2ec] px-5 py-20 text-[#102019] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.75fr_1.25fr]"><Reveal><p className="eyebrow text-xs text-[#526653]">What CannumX is</p></Reveal><Reveal delay={.1}><p className="text-3xl leading-[1.15] tracking-[-.045em] sm:text-4xl">We are not limited to one industry or one service. We find the growth constraint holding your business back—and assemble the right answer to solve it.</p><p className="mt-7 max-w-2xl text-lg leading-8 text-[#102019]/65">That may mean an acquisition system, a sharper sales process, a recovery campaign, a purpose-built automation, or a digital product. You work with one growth partner while we own the strategy, execution, and quality.</p></Reveal></div></section>

    <section id="services" className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><Reveal><div className="flex flex-col justify-between gap-5 border-b border-white/15 pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-xs text-[#caff5a]">Capabilities</p><h2 className="editorial-title mt-3 text-5xl tracking-[-.07em] sm:text-7xl">The growth<br />toolkit.</h2></div><p className="max-w-sm text-white/55">Expert services, trusted fulfilment partners, and proprietary AI systems—selected for the result, not the label.</p></div></Reveal><div className="divide-y divide-white/15">{capabilities.map((capability, i) => <Reveal key={capability.title} delay={i * .04}><article className="group grid gap-5 py-7 transition sm:grid-cols-[70px_1fr_auto] sm:items-start"><div className="font-mono text-xs text-[#caff5a]">{capability.number}</div><div><div className="flex items-center gap-3"><capability.icon size={21} className="text-[#caff5a]" /><h3 className="text-2xl tracking-[-.045em]">{capability.title}</h3></div><div className="mt-5 grid gap-2 text-sm text-white/55 sm:grid-cols-2">{capability.items.map(item => <span key={item} className="flex items-center gap-2"><Check size={13} className="text-[#caff5a]" />{item}</span>)}</div></div><ArrowUpRight className="hidden text-white/40 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#caff5a] sm:block" /></article></Reveal>)}</div></div></section>

    <section id="how-it-works" className="bg-[#1c362b] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow text-xs text-[#caff5a]">How we operate</p><div className="mt-4 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="editorial-title max-w-3xl text-5xl tracking-[-.07em] sm:text-7xl">One partner.<br />The right solution.</h2><p className="max-w-sm text-white/60">Every engagement is built around your goal. Delivery may be handled by our in-house team, vetted white-label specialists, or CannumX software.</p></div></Reveal><div className="mt-14 grid gap-px overflow-hidden border border-white/15 bg-white/15 md:grid-cols-4">{process.map(([number, title, description], i) => <Reveal key={title} delay={i * .07}><div className="min-h-64 bg-[#1c362b] p-7"><span className="font-mono text-xs text-[#caff5a]">{number}</span><h3 className="mt-16 text-2xl tracking-[-.04em]">{title}</h3><p className="mt-4 leading-7 text-white/55">{description}</p></div></Reveal>)}</div></div></section>

    <section id="industries" className="bg-[#f3f2ec] px-5 py-20 text-[#102019] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><Reveal><div className="grid gap-8 lg:grid-cols-2"><h2 className="editorial-title text-5xl tracking-[-.07em] sm:text-7xl">Growth is<br />industry-agnostic.</h2><div><p className="text-lg leading-8 text-[#102019]/70">We specialise in the underlying systems that move service businesses forward: demand, follow-up, conversion, retention, and delivery.</p><p className="mt-5 font-serif text-2xl italic">If qualified leads, revenue, or operational efficiency matter, we can help.</p></div></div></Reveal><div className="mt-14 grid border-l border-t border-[#102019]/15 sm:grid-cols-2 lg:grid-cols-3">{industries.map((industry, i) => <Reveal key={industry} delay={i * .025}><div className="border-b border-r border-[#102019]/15 p-5 text-sm transition hover:bg-[#caff5a]">{industry}</div></Reveal>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 border-y border-white/15 py-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="eyebrow text-xs text-[#caff5a]">Long-term vision</p></Reveal><Reveal delay={.1}><h2 className="editorial-title text-5xl tracking-[-.07em] sm:text-7xl">Services today.<br /><em className="font-serif font-normal text-[#caff5a]">Technology</em> tomorrow.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-white/60">As we solve recurring challenges across industries, we turn what works into proprietary AI agents, automation platforms, and software products. CannumX is building toward a future where expert execution and technology compound together.</p></Reveal></div></section>

    <section id="contact" className="px-5 pb-5 pt-10 sm:px-8 lg:px-12"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-[#caff5a] px-6 py-16 text-[#102019] sm:px-12 lg:px-16 lg:py-20"><div className="absolute -right-20 -top-20 h-80 w-80 rounded-full border-[50px] border-[#102019]/10" /><Reveal><p className="eyebrow text-xs">Start with the real problem</p><h2 className="editorial-title relative mt-5 max-w-4xl text-5xl tracking-[-.08em] sm:text-7xl lg:text-8xl">What would change your business this year?</h2><p className="relative mt-7 max-w-xl text-lg leading-8 text-[#102019]/70">Tell us where growth is getting stuck. We&apos;ll help you identify the most valuable next move.</p><Link href="/contact" className="button-dark relative mt-10 inline-flex items-center gap-3 rounded-full px-6 py-3.5 font-semibold transition">Book a strategy call <ArrowUpRight size={18} /></Link></Reveal></div></section>

    <section id="faq" className="px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.7fr_1.3fr]"><h2 className="editorial-title text-5xl tracking-[-.07em]">A few things<br />you may ask.</h2><div className="divide-y divide-white/15">{[["Do you only provide AI solutions?", "No. We choose the right lever for your business goal—whether that is sales systems, lead generation, recovery campaigns, automation, a website, or a wider growth strategy."],["Who delivers the work?", "CannumX manages every engagement. Depending on the project, delivery is handled by our internal team, trusted white-label specialists, or our proprietary systems."],["Do you work with our existing tools?", "Usually. We build around the tools, team, and process you already have unless a change is clearly necessary."],["What happens first?", "We begin by understanding your goals and current bottlenecks, then recommend the highest-value path forward."]].map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-lg"><span>{question}</span><ChevronDown className="transition group-open:rotate-180" size={19} /></summary><p className="max-w-2xl pt-4 leading-7 text-white/55">{answer}</p></details>)}</div></div></section>
  </main>;
}
